### ISSUE TITLE
Deserialization errors after upgrading from Rails 4.2 to 5.1+

### ISSUE THREAD

**Issue by drewB** [collectiveidea/delayed_job#1111]
I am working on upgrading an app from Rails 4.2 to 5.2.  I have am running into an issue were jobs that were created in 4.2 are raising errors when they are invoked under Rails 5.2.  

`Delayed::DeserializationError (Job failed to load: not delegated...`

I have narrowed it down to a problem after moving from 5.0 to 5.1.  In 5.0.7 there is no problem but there is in 5.1.0.  I can reproduce on a simple test case (taken from job.handler) by doing `YAML.load(yml)` where yml:

```
object: !ruby/object:Account
  raw_attributes:
    id: '8469'
  attributes: !ruby/object:ActiveRecord::AttributeSet
    attributes: !ruby/object:ActiveRecord::LazyAttributeHash
      types:
        id: &4 !ruby/object:ActiveRecord::Type::Integer
          precision: 
          scale: 
          limit: 8
          range: !ruby/range
            begin: -9223372036854775808
            end: 9223372036854775808
            excl: true
      values:
        id: '8469'
        created_at: '2019-11-15 21:16:15.257401'
      additional_types: {}
      materialized: true
      delegate_hash:
        id: !ruby/object:ActiveRecord::Attribute::FromDatabase
          name: id
          value_before_type_cast: '8469'
          type: *4
          value: 8469
        created_at: !ruby/object:ActiveRecord::Attribute::FromDatabase
          name: created_at
          value_before_type_cast: '2019-11-15 21:16:15.257401'
          type: !ruby/object:ActiveRecord::AttributeMethods::TimeZoneConversion::TimeZoneConverter
            subtype: !ruby/object:ActiveRecord::ConnectionAdapters::PostgreSQL::OID::DateTime
              precision: 
              scale: 
              limit: 
          value: 2019-11-15 21:16:15.257401000 Z
  new_record: false
  active_record_yaml_version: 0
```

That gives the error `ArgumentError (not delegated)`.  I have found that removing the `subtype` under created_at makes the problem go away but not idea why.  I have tried changing the subtype to something simple like an integer and get the same problem.

Anyone have thoughts on how to approach this?  I am really surprised that I have not found any info on others running into the same problem.
