### ISSUE TITLE
Rails 3 email not sent; is using PerformableMethod rather than PerformableMailer

### ISSUE THREAD

**Issue by szTheory** [collectiveidea/delayed_job#267]
If I disable delayed jobs in the config file, the email sends just fine. Also another non-mailer delayed job is working fine. My delayed_jobs table is properly being populated with the job.

When I check the worker output everything looks hunky-dory as well (Lead is the non-mailer delayed job that's working correctly)

```
[Worker(host:My-Mac.local pid:6156)] Lead completed after 4.7002
[Worker(host:My-Mac.local pid:6156)] Class#lead_received completed after 0.0194
[Worker(host:My-Mac.local pid:6156)] 2 jobs processed at 0.4231 j/s, 0 failed ...
```

I'm using the 2.1.4 gem. I've checked out the head and 2.1.4 code to run the specs and the relevant PerformableMailer tests are passing, so I'm not sure what's up.

`gem list --local delayed_job`

```
*** LOCAL GEMS ***

delayed_job (2.1.4)
```

Here is the code being used to send the email:

```
Notifications.delay.lead_received(@contact)
```

Here is the serialized YAML from the delayed_job "handler" field:

```
yaml: --- !ruby/struct:Delayed::PerformableMethod 
object: !ruby/class Notifications
method_name: :lead_received
args: 
- !ruby/ActiveRecord:Lead 
  attributes: 
    full_name: McFly Fearsome
    company: Omega Inc
```

The mailer is just a simple ActionMailer::Base

```
class Notifications < ActionMailer::Base

  default :from => "test@test.com"

  def lead_received(contact)
    @contact = contact
    mail :to => contact.email, :subject => 'We received your information'
  end
end
```

Any ideas?
