### ISSUE TITLE
YAML parsing issue psych vs syck

### ISSUE THREAD

**Issue by zatmonkey** [collectiveidea/delayed_job#544]
Hi,

most of the time all goes well in delayed:job (I use     delayed_job (3.0.5) )
I use by default psych as yaml parser
but sometimes it just fails to load the handler with a 

```
    ArgumentError: wrong number of arguments (2 for 1)
            from /home/diveboard/diveboard-web/shared/bundle/ruby/1.9.1/gems/ruby-units-1.4.0/lib/ruby_units/time.rb:15:in `at'
            from /usr/lib/ruby/1.9.1/psych/scalar_scanner.rb:125:in `parse_time'
            from /usr/lib/ruby/1.9.1/psych/scalar_scanner.rb:48:in `tokenize'
            from /home/diveboard/diveboard-web/shared/bundle/ruby/1.9.1/gems/delayed_job-3.0.5/lib/delayed/psych_ext.rb:47:in `visit_Psych_Nodes_Scalar'
            from /usr/lib/ruby/1.9.1/psych/visitors/visitor.rb:15:in `visit'
            from /usr/lib/ruby/1.9.1/psych/visitors/visitor.rb:5:in `accept'
            from /usr/lib/ruby/1.9.1/psych/visitors/to_ruby.rb:20:in `accept'
            from /usr/lib/ruby/1.9.1/psych/visitors/to_ruby.rb:266:in `block in revive_hash'
            from /usr/lib/ruby/1.9.1/psych/visitors/to_ruby.rb:251:in `each'
            from /usr/lib/ruby/1.9.1/psych/visitors/to_ruby.rb:251:in `each_slice'
            from /usr/lib/ruby/1.9.1/psych/visitors/to_ruby.rb:251:in `revive_hash'
            from /usr/lib/ruby/1.9.1/psych/visitors/to_ruby.rb:141:in `visit_Psych_Nodes_Mapping'
            from /home/diveboard/diveboard-web/shared/bundle/ruby/1.9.1/gems/delayed_job-3.0.5/lib/delayed/psych_ext.rb:125:in `visit_Psych_Nodes_Mapping_with_class'
            from /usr/lib/ruby/1.9.1/psych/visitors/visitor.rb:15:in `visit'
            from /usr/lib/ruby/1.9.1/psych/visitors/visitor.rb:5:in `accept'
            from /usr/lib/ruby/1.9.1/psych/visitors/to_ruby.rb:20:in `accept'
    ... 10 levels...
            from /home/diveboar
```

and of course forcing the yaml parser to syck solves the issue

here's a sample handler that fails 

``` yaml
--- !ruby/object:Delayed::PerformableMethod
object: !ruby/ActiveRecord:Dive
  attributes:
    id: 74727
    time_in: 2013-07-03 11:27:00.000000000 +02:00
    duration: 27
    profile_data: 
    created_at: 2013-07-09 13:58:49.000000000 Z
    updated_at: 2013-07-17 13:18:09.643470592 Z
    user_id: 18341
    graph_id: 
    spot_id: 2239
    maxdepth: 9.0
    notes: ! ' some text
      some text'
    temp_surface: 22.0
    temp_bottom: 22.0
    favorite_picture: 
    privacy: 1
    safetystops: ! '[["3","1"]]'
    divetype: ! '["training"]'
    favorite: 0
    uploaded_profile_id: 
    uploaded_profile_index: 
    buddies: 
    visibility: bad
    water: salt
    altitude: 0.0
    weights: 7.0
    dan_data: ! '{"version":1,"encrypted":false,"diver":{"dan_pde_id":null,"dan_id":null,"alias":null,"mother":null,"sex":null,"birthday":null,"email":null,"language":null,"citizenship":null,"first_certif":null,"certif_level":null,"dives_12m":null,"dives_5y":null,"conditions":null,"medications":null,"cigarette":null,"name":[null,null,null,null,null,null],"birthplace":[null,null,null],"address":[null,null,null,null,null,null],"phone_home":[null,null],"phone_work":[null,null],"license":[null,null],"weight":[null,"2"],"height":[null,"2"]},"dive":{"dive_plan":null,"dive_plan_table":null,"rest":null,"drinks":null,"exercice":null,"med_dive":null,"purpose":null,"program":null,"environment":null,"platform":null,"thermal_confort":null,"workload":null,"decompression":null,"problems":null,"malfunction":null,"symptoms":null,"comments":null,"altitude_exposure":null,"altitude_interval":null,"altitude_date":null,"altitude_length":null,"altitude_value":null,"hyperbar":null,"hyperbar_location":null,"hyperbar_number":null,"bottom_gas":null,"gases_number":0,"gases":[],"visibility":5,"dress":2,"apparatus":1,"current":0},"sent":false,"previous":null}'
    current: none
    dan_data_sent: 
    number: 6
    graph_lint: 
    shop_id: '1010'
    guide: Ugo
    trip_id: 6166
    album_id: 64617
    score: 3
method_name: :fb_lint_me_without_delay
args: []
```
